Delete your Status Community
status-im/help.status.im pull request #567
Opened 2023-04-18 08:55 UTC by cheny0

2023-04-19 13:50 UTC, jorge-campo requested changes
And the `index.md` entry ? :)

Thanks for the article, @cheny0 - Simple and to-the-point. 

I only have a few suggestions that I think can improve the article's readability.

2023-04-19 13:50 UTC, jorge-campo commented on docs/en/status-communities/delete-your-status-community.md
> +- [x] [Kick all members from the community][kick-or-ban-someone-from-your-community].
```suggestion
- [x] [Kick out all members from the community][kick-or-ban-someone-from-your-community].
```

2023-04-19 13:50 UTC, jorge-campo commented on docs/en/status-communities/delete-your-status-community.md
> +
```suggestion

After 30 days, the Waku peer-to-peer network stops caching your community data, and the community is deleted irrecoverably.

```

2023-04-20 07:37 UTC, merged

2023-04-20 07:53 UTC, cheny0 commented
> And the `index.md` entry ? :)
> 
> Thanks for the article, @cheny0 - Simple and to-the-point.
> 
> I only have a few suggestions that I think can improve the article's readability.

Thanks! I have applied the changes and merged the article into `develop` and `master`.